trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Day2/incubyte_blog/*

pool:
  vmImage: ubuntu-latest

variables:
  projectDir: 'Day2/incubyte_blog'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'
  workingDirectory: $(projectDir)

- script: npm test -- --ci
  displayName: 'Run unit tests'
  workingDirectory: $(projectDir)